enhancement: better messaging for K6 not installed
k6io/chaostoolkit-k6 pull request #6
Opened 2021-10-25 19:31 UTC by geekusa33

Improve the message for when the k6 binary isn't found in the PATH,  used try, except to handle exception. 

I think this should resolve issue #4

2021-10-25 23:42 UTC, ppcano requested changes

2021-10-26 15:03 UTC, Lawouach requested changes
Please also add a changelog entry and, hopefully a test.

2022-06-15 17:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/chaostoolkit-k6?pullRequest=6) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/chaostoolkit-k6?pullRequest=6) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/chaostoolkit-k6?pullRequest=6) it.</sub>

2026-06-05 11:17 UTC, tleopold commented
Closing this pull request: the repository is being archived and transferred to cold storage.

2026-06-05 11:17 UTC, closed without merging